---
title: Guide to my country 3.0
hero_image: images/banner.png
description: Adăugați machete frumoase și efecte interesante pe site-ul dvs.!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-JavaScript
site_areas: coderdojo, proiecte
software: html-css-JavaScript
version: 4.0.1
last_tested: 01-01-2017
steps:
  - 
    title: Introducere
  - 
    title: Getting setup
  - 
    title: Clickable cards
  - 
    title: All in a row
  - 
    title: Make your menu responsive
  - 
    title: Captions and side notes
  - 
    title: Design cool page layouts
  - 
    title: Photo collage
  - 
    title: Special effects
