---
title: Ghid pentru țara mea 3.0
hero_image: images/banner.png
description: Adaugă modele drăguțe si efecte atractive site-ului tău!
theme: roșu #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, projects
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: De pregătit
  - 
    title: Cartonașe de accesat
  - 
    title: Toate pe rând
  - 
    title: Creează un meniu receptiv
  - 
    title: Legende si notițe
  - 
    title: Creează modele de pagini atractive
  - 
    title: Album foto
  - 
    title: Efecte speciale
