---
title: Guide to my country 3.0
hero_image: imagens/banner.png
description: Add nice layouts and cool effects to your website!
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, projects
software: html-css-javascript
version: 4.1.0
last_tested: 01/01/2017
steps:
  - 
    title: Introdução
  - 
    title: Getting setup
  - 
    title: Clickable cards
  - 
    title: All in a row
  - 
    title: Make your menu responsive
  - 
    title: Captions and side notes
  - 
    title: Design cool page layouts
  - 
    title: Photo collage
  - 
    title: Special effects
