---
title: Guía de mi país 3.0
hero_image: images/banner.png
description: '¡Agregue diseños agradables y efectos geniales a su sitio web!'
theme: rojo #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: proyectos de CoderDojo
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Robot parlanchín
  - 
    title: Preparación
  - 
    title: Tarjetas interactivas
  - 
    title: Consecutivamente
  - 
    title: Haz tu menú adaptable
  - 
    title: Leyendas y notas al margen
  - 
    title: Diseña plantillas de página interesantes
  - 
    title: Collage de fotos
  - 
    title: Efectos especiales
