---
title: Carte di sushi HTML / CSS avanzate
hero_image: images / banner.png
description: Aggiungi bei layout e fantastici effetti al tuo sito web!
theme: rosso
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, progetti
software: html-css-javascript
version: 4.1.0
last_tested: 2017/01/01
steps:
  - 
    title: introduzione
  - 
    title: Getting setup
  - 
    title: Clickable cards
  - 
    title: All in a row
  - 
    title: Make your menu responsive
  - 
    title: Captions and side notes
  - 
    title: Design cool page layouts
  - 
    title: Photo collage
  - 
    title: Special effects
